# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GDEmu/Rhea/Phoebe中文使用教程
email: sonic3d@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  本站点用语介绍GDEmu/Rhea/Phoebe的使用
  <br>本站点不确保内容是否准确或最新，使用风险自担
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  SONIC3D

# options for minima theme
author: SONIC3D

# options for jekyll-theme-midnight theme
show_github_project_headerbar: false
show_downloads: false
google_analytics: false
github:
  owner_url: http://gdemu.emu.wiki
  owner_name: SONIC3D

# Build settings
markdown: kramdown
show_drafts: false
# theme: minima
theme: jekyll-theme-midnight
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
